import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css"
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import { getAuthenticatedUserCart } from "@/actions/cart.actions";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  const result = await getAuthenticatedUserCart({userId: session?.user?.id as string})
  return (
    
        <main className="min-h-screen w-full">
           <Header qty={result.data?.qty} data={result.data?.userCart} />
  {children}
  <Footer />
       
        </main>
      
     
  );
}
